### DISCUSSION TITLE
M5Stack Lite/HA/ESPHome/Roamer Series 3 160Ah

### DISCUSSION THREAD

**Discussion by virtualwebber** [syssi/esphome-basen-bms#46] [General]
I came across this when looking for a way to monitor my Roamer Battery via HA. I am fairly new to HA/ESP, but hoping I can get some guidance to get this working :).  I have tried setting up the M5Stack Atom Lite as a generic ESP32 device and tried using the example Yaml, but ESPHome doesn't like the syntax. Is it possible someone might be good enough to give me a pointer on where to start to get this device in ESPHome with the right configuration to get it into HA? I already have a MQTT broker set up as I am using that with a Theengs Gateway/Bridge. Thankyou

**Comment by virtualwebber** [comment]
Think I got it sorted, by using this configuration. I assume the MAC address is the device I want to monitor? Any pointers on how to get the Roamer Battery showing/connected as currently it isn't detecting anything in HA. Apologies if that is a stupid question!

```
substitutions:
  name: m5stack-atom-lite-08aee8
  friendly_name: Bluetooth Proxy 08aee8
  device_description: "Monitor a Roamer Battery Management System via BLE"
  external_components_source: github://syssi/esphome-basen-bms@main
  mac_address: "20:00:00:00:09:06"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

external_components:
  - source: ${external_components_source}
    refresh: 0s

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:
  encryption:
    key: Rpla6A2T1Q8HODGssGzhtPXrogWSaICthF5yHTUlnOg=

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${mac_address}
    id: client0

basen_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 10s

binary_sensor:
  - platform: basen_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

sensor:
  - platform: basen_bms_ble
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    charging_states_bitmask:
      name: "${name} charging states bitmask"
    discharging_states_bitmask:
      name: "${name} discharging states bitmask"
    charging_warnings_bitmask:
      name: "${name} charging warnings bitmask"
    discharging_warnings_bitmask:
      name: "${name} discharging warnings bitmask"
    state_of_charge:
      name: "${name} state of charge"
    nominal_capacity:
      name: "${name} nominal capacity"
    nominal_voltage:
      name: "${name} nominal voltage"
    real_capacity:
      name: "${name} real capacity"
    serial_number:
      name: "${name} serial number"
    charging_cycles:
      name: "${name} charging cycles"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"

text_sensor:
  - platform: basen_bms_ble
    charging_states:
      name: "${name} charging states"
    discharging_states:
      name: "${name} discharging states"
    charging_warnings:
      name: "${name} charging warnings"
    discharging_warnings:
      name: "${name} discharging warnings"
    manufacturing_date:
      name: "${name} manufacturing date"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

  - platform: basen_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
```

**Comment by virtualwebber** [comment]
Think have it working as getting the following read outs from a Roamer 160Ah S3 (have disabled a lot of the sensors as were showing as unknown):-

![image](https://github.com/user-attachments/assets/13a17649-9b92-4229-a041-bd0a5b4b76e3)

**Reply by syssi** [reply]
Good job!

**Comment by virtualwebber** [comment]
Configuration I used 
```
substitutions:
  name: m5stack-atom-lite-08aee8
  friendly_name: Roamer BMS Monitor
  device_description: "Roamer BMS Monitor"
  external_components_source: github://syssi/esphome-basen-bms@main
  mac_address: "20:00:00:00:09:06"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:
  level: INFO

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

external_components:
  - source: ${external_components_source}
    refresh: 0s

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      manual_ip: 
        static_ip: 192.168.254.50
        gateway: 192.168.254.1
        subnet: 255.255.255.0
        dns1: 192.168.254.1
  use_address: 192.168.254.50

ota:
  - platform: esphome

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${mac_address}
    id: client0

basen_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 900s

binary_sensor:
  - platform: basen_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

sensor:
  - platform: basen_bms_ble
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    charging_states_bitmask:
      name: "${name} charging states bitmask"
    discharging_states_bitmask:
      name: "${name} discharging states bitmask"
    charging_warnings_bitmask:
      name: "${name} charging warnings bitmask"
    discharging_warnings_bitmask:
      name: "${name} discharging warnings bitmask"
    state_of_charge:
      name: "${name} state of charge"
    nominal_capacity:
      name: "${name} nominal capacity"
    nominal_voltage:
      name: "${name} nominal voltage"
    real_capacity:
      name: "${name} real capacity"
    serial_number:
      name: "${name} serial number"
    charging_cycles:
      name: "${name} charging cycles"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
 
text_sensor:
  - platform: basen_bms_ble
    charging_states:
      name: "${name} charging states"
    discharging_states:
      name: "${name} discharging states"
    charging_warnings:
      name: "${name} charging warnings"
    discharging_warnings:
      name: "${name} discharging warnings"
    manufacturing_date:
      name: "${name} manufacturing date"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

  - platform: basen_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"`
```
