### DISCUSSION TITLE
BLE Update Interval

### DISCUSSION THREAD

**Discussion by virtualwebber** [syssi/esphome-basen-bms#48] [General]
On the configuration am I correct in assuming this value is saying the BLE Proxy will scan the BLE device every 10seconds and update the sensors?

```
basen_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 10s

```
and if i update the interval value to 3600s, then that would be it scans every hour?
`update_interval: 3600s`
