### ISSUE TITLE
Negative temperature readings show incorrectly

### ISSUE THREAD

**Issue by will-h** [syssi/esphome-basen-bms#29]
Looks like the temperature is actually a signed int. The provided Roamer android app says my BMS temperature is -2°C, but esphome-basen-bms reports 254°C.

`[13:33:22][D][sensor:094]: 'basen-bms-ble temperature 1': Sending state 254.00000 °C with 0 decimals of accuracy`

**Comment by syssi** [comment]
I've pushed a fix to a feature branch. Please update your YAML (temporary) from:

```
substitutions:
  name: basen-bms-ble
  device_description: "Monitor a Basen Battery Management System via BLE"
  external_components_source: github://syssi/esphome-basen-bms@main
```

to 

```
substitutions:
  name: basen-bms-ble
  device_description: "Monitor a Basen Battery Management System via BLE"
  external_components_source: github://syssi/esphome-basen-bms@fix-temperatures
```

Please flash your ESP another time and give it a try. Does this change fix the issue?
